root = "."
tmp_dir = "tmp"

[build]
bin = "tmp/bloggulus"
pre_cmd = ["tailwindcss -o public/css/tailwind.min.css --minify"]
cmd = "go build -o ./tmp/bloggulus main.go"
include_ext = ["go", "html"]
include_dir = ["backend"]
include_file = ["main.go"]

[proxy]
enabled = false
