root = "."
tmp_dir = "tmp"

[build]
bin = "tmp/bloggulus"
cmd = "go build -o ./tmp/bloggulus main.go"
include_ext = ["go", "html", "css"]
include_dir = ["backend", "public"]
include_file = ["main.go"]

[proxy]
enabled = false
