before:
  hooks:
    - go mod tidy

builds:
  - main: cmd/web/main.go
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64

archives:
  - name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    files:
      - none*
    format_overrides:
      - goos: windows
        format: zip

nfpms:
  - package_name: bloggulus
    file_name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    homepage: https://github.com/theandrew168/bloggulus
    maintainer: Andrew Dailey <andrew@shallowbrooksoftware.com>
    description: A website for avid blog readers
    license: MIT
    formats:
      - deb
    bindir: /usr/bin
    contents:
      - src: script/bloggulus.service
        dst: /lib/systemd/system/bloggulus.service
        type: config
      - src: script/bloggulus.conf
        dst: /etc/bloggulus.conf
        type: config
    scripts:
      postinstall: script/postinstall.sh
      preremove: script/preremove.sh
      postremove: script/postremove.sh

checksum:
  name_template: checksums.txt

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
