# Generated by Django 3.1.1 on 2020-09-10 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Entry',
            new_name='Post',
        ),
    ]
