# Generated by Django 3.1.1 on 2020-09-11 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0002_auto_20200910_2213'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feed',
            name='author',
        ),
    ]
