# Generated by Django 3.1.1 on 2020-09-12 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0003_remove_feed_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='url',
            field=models.URLField(unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='url',
            field=models.URLField(unique=True),
        ),
    ]
