# Generated by Django 3.1.1 on 2020-09-13 04:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('feeds', '0004_auto_20200912_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='feeds', to=settings.AUTH_USER_MODEL),
        ),
    ]
