name: Test

on: [push, pull_request]

jobs:
  deploy:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v7
      - name: Start containers
        run: docker compose up -d
      - name: Setup Go
        uses: actions/setup-go@v7
        with:
          go-version: "1.27"
      - name: Run tests
        run: make test
